# "$schema" = 'https://starship.rs/config-schema.json'

format = "$character $directory$git_branch"

scan_timeout = 10

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[➜](bold red)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

[directory]
format = '[$path]($style) '
truncation_length = 1

[git_branch]
format = '''[git:\([$branch]($style)\)](bold blue) '''
# [git:\(](bold blue)[$branch]($style)[\)](bold blue) 
style = "bold red"
